### ISSUE TITLE
Bug with Demand Charge Calculation using sub-hourly data

### ISSUE THREAD

**Issue by nickdiorio** [NREL/ssc#116]
In the event that one-minute weather and load data are used, and multiple TOU demand periods are defined, the TOU demand charges which are calculated are incorrrect.  If there is only one TOU demand period, the charges are calculated correctly.

**Comment by cpaulgilman** [comment]
This turns out not to be a bug, but to be a reporting issue. For demand charge structures with TOU periods,  California utilities calculate total monthly demand charge as sum of charge in each TOU period. See Slide 11 at https://www.slideshare.net/stem_marketing/20130514-demand-charges-overview-for-slideshare#https://www.slideshare.net/stem_marketing/20130514-demand-charges-overview-for-slideshare
