### ISSUE TITLE
cf_ptc_total doesn't work

### ISSUE THREAD

**Issue by dguittet** [NREL/ssc#644]
**Describe the bug**
I assume `cf_ptc_total` = `cf_ptc_fed` + `cf_ptc_sta` but the total seems to be 0 even when fed is non-zero.

**To Reproduce**
1. Open default Wind Single Owner case (Federal PTC will be active)
2. Click on 'Simulate'
3. Try out this script: 
![image](https://user-images.githubusercontent.com/29387736/140619622-e8fa44ec-e0b3-4043-b6a7-3e3b10b00f29.png)

**Comment by cpaulgilman** [comment]
I think `cf_ptc_total` should be removed because the state PTC and federal PTC are treated separately in the cash flow: The the state PTC is taxable income for Federal tax purposes. For example, see [here](https://github.com/NREL/ssc/blob/9cf27a1bb29f9488eb1b13f95a3ce35315d3ea9b/ssc/cmod_singleowner.cpp#L2721) for Single Owner. So the total PTC (sum of State and Federal) does not really have significance for cash flow calculations.

The total PTC is only calculated by cmod_cashloan, but not used to calculate any results. It is assigned as an output in common,cpp, but not assigned a value in any of the financial model compute modules.

Solution is to remove `cf_ptc_total` from common,cpp and cmod_cashloan.cpp.

LK Script for testing with Wind / Single Owner:

```
a = get('cf_ptc_fed');
b = get('cf_ptc_sta');
c = get('cf_ptc_total');
d = get('itc_total'); // not relevant for this conversation

outln(a);
outln(b);
outln(c);
outln(d);
```

**Comment by dguittet** [comment]
@cpaulgilman Thanks for the explanation!
