### ISSUE TITLE
CMPvsamv1BatteryIntegration_cmod_pvsamv1.ResidentialDCBatteryModelPriceSignalDispatch faling on Travis and runs fine on Windows

### ISSUE THREAD

**Issue by sjanzou** [NREL/ssc#675]
The one failing test runs fine on Windows
<img width="606" alt="image" src="https://user-images.githubusercontent.com/6498311/143821069-4b899b0c-cdad-4253-8f24-cc65967f9fec.png">

Retesting on Travis running single test     ::testing::GTEST_FLAG(filter) = "CMPvsamv1BatteryIntegration_cmod_pvsamv1.ResidentialDCBatteryModelPriceSignalDispatch";
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/6498311/143823668-7fdd039d-edab-4b67-845d-f8d4a3252b04.png">

batt_DOD_cycle_average output difference - separate issue
27.29 on Windows 
27.52 on Travis

_Originally posted by @sjanzou in https://github.com/NREL/ssc/issues/673#issuecomment-981348314_

**Comment by dguittet** [comment]
It passes on Mac also with value 27.290548

**Comment by brtietz** [comment]
This appears to be a recurrence of issue https://github.com/NREL/ssc/issues/614 - the linux and windows implementations end up with slightly different dispatch patterns. 

With the defaults currently in the GUI, windows schedules dispatch for step 966 but not 967, whereas Linux does the reverse. This causes the SOC to diverge, with greater divergence in the dispatch plan from there. It amounts to about 4 out of 926 kWh in year 1.

Interestingly, the Linux test is displaying the old value: https://github.com/NREL/ssc/commit/442ea5b6a787f75335aece7199efb6f442f943d3 Unfortunately due to the Travis outages I can't see if that commit caused the test failure or if the error was introduced a few days earlier and that's when it was exposed.

Would it be acceptable to increase the tolerance on the test for now and clean this up after the release? I created a branch addtl_lifetime_testing_in_integration_tests that shows that this issue is restricted to price signals dispatch - we could merge that in for additional test coverage of cycling differences between platforms.

**Comment by brtietz** [comment]
I checked out 314cb53e0 (from Nov 17th, before the anti-reflective glass change) and the test passes there. This means that the dispatch changes in https://github.com/NREL/ssc/pull/662 exposed the Linux failure and my fix to https://github.com/NREL/ssc/issues/614 is insufficient.

I think this is a strong argument for a tolerance increase for this release, and to re-open https://github.com/NREL/ssc/issues/614 for a more robust solution in the future.

**Comment by sjanzou** [comment]
That seems like a reasonable solution for the release…
